
language: php

php:
    - "5.4"

before_script:
    - curl -s https://getcomposer.org/installer | php
    - php composer.phar install --dev

script:
    - bin/phpunit -c tests/unit/phpunit.xml tests/unit/
    - bin/phpunit -c tests/infrastructure/phpunit.xml tests/infrastructure/
#    - bin/phpcs --standard=PSR2 tests/unit/ src/
