
language: php

php:
    - "5.4"

before_script:
    - curl -s https://getcomposer.org/installer | php
    - php composer.phar install --prefer-source


script:
    - vendor/bin/phpunit -c tests/unit/phpunit.xml tests/unit/

