<?php
$loginForm = $this->loginForm->prepare()
    ->setAttributes(['method' => 'post', 'action' => $this->action, 'class' => 'form-vertical', 'novalidate' => true]);
$loginForm->get('email')
    ->setAttributes(['placeholder' => 'Email Address', 'id' => 'email', 'class' => 'form-control input-lg']);
$loginForm->get('password')
    ->setAttributes(['placeholder' => 'Password', 'id' => 'password', 'class' => 'form-control input-lg']);
?>

<div class="container">
    <div class="row" style="margin-top:20px">
        <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
            <?= $this->form()->openTag($loginForm) ?>
                <fieldset>
                    <img alt="" src="/images/logo-lg.png">
                    <hr class="login">
                    <div class="form-group">
                        <?= $this->formInput($loginForm->get('email')); ?>
                        <?= $this->formElementErrors($loginForm->get('email')) ?>
                    </div>
                    <div class="form-group">
                        <?= $this->formInput($loginForm->get('password')); ?>
                    </div>

                    <hr class="login">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <button type="submit" class="btn btn-lg btn-block btn-default">Sign In</button>
                        </div>
                    </div>
                </fieldset>
            <?= $this->form()->closeTag($loginForm) ?>
        </div>
    </div>
</div>
