<table class="table table-striped">
    <tr>
        <th>Type</th>
        <th>Date</th>
        <th>Place</th>
        <th></th>
    </tr>
    <?php foreach ($this->person->getEvents() as $event): ?>
        <tr>
            <td><?= $event->getType()->getName() ?></td>
            <td><?= $event->getDate() ?></td>
            <td><?= $event->getPlace() ?></td>
            <td>
                <div class="btn-toolbar pull-right" role="toolbar">
                    <div class="btn-group btn-group-sm">
                        <button type="button" class="event-sources btn btn-success"
                            data-toggle="modal" data-target="#event-sources-modal"
                            data-url="/people/events/sources/<?= $event->getId() ?>"
                            data-id="<?= $event->getId() ?>">
                            <i class="fa fa-book"></i> &nbsp;
                            Sources &nbsp;
                            <span class="badge"><?= count($event->getSources()) ?></span>
                        </button>
                        <button type="button" class="btn btn-success">
                            <i class="fa fa-pencil"></i> &nbsp;
                            Notes &nbsp;
                            <span class="badge">???</span>
                        </button>
                        <button type="button" class="btn btn-danger"><i class="fa fa-trash-o"></i></button>
                    </div>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<button class="btn btn-primary btn-sm pull-right" data-toggle="modal" data-target="#add-event-modal">Add Event</button>
<div class="clearfix"></div>
