<table class="table table-striped">
    <tr>
        <th>Source</th>
        <th>Page</th>
        <th>Text</th>
        <th></th>
    </tr>
    <?php foreach ($this->event->getSources() as $source): ?>
        <tr>
            <td><?= $source->getSource()->getName() ?></td>
            <td><?= $source->getPage() ?></td>
            <td>???</td>
            <td>
                <div class="btn-toolbar pull-right" role="toolbar">
                    <div class="btn-group btn-group-sm">
                        <button type="button" class="event-sources btn btn-success">
                            <i class="fa fa-pencil"></i>
                        </button>
                        <button type="button" class="btn btn-danger">
                            <i class="fa fa-trash-o"></i>
                        </button>
                    </div>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
