<table class="table table-striped">
    <tr>
        <th>Source</th>
        <th>Page</th>
        <th>Text</th>
        <th></th>
    </tr>
    <?php foreach ($this->event->getSources() as $source): ?>
        <tr>
            <td><?= $source->getSource()->getName() ?></td>
            <td><?= $source->getPage() ?></td>
            <td>???</td>
            <td></td>
        </tr>
    <?php endforeach; ?>
</table>

<!--<button class="btn btn-primary btn-sm pull-right" data-toggle="modal" data-target="#add-event-modal">Add Event</button>-->
<!--<div class="clearfix"></div>-->
