
<h2>People</h2>

<form class="form-search">
    <input type="text" class="input-medium search-query">
    <button type="submit" class="btn">Search</button>
</form>

<table class="table table-striped table-hover">
    <thead>
        <th>Name</th>
        <th>Born</th>
        <th>Died</th>
        <th>Mother</th>
        <th>Father</th>
        <th>&nbsp;</th>
    </thead>
    <tbody>
        <?php foreach ($this->people as $person): ?>
        <tr>
            <td>
                <a href="/people/view/<?= $person->getId(); ?>">
                    <?= $person->getConfirmedName()->getSurnameFirst(); ?></a>
            </td>
            <td>
                <?php if ($person->getConfirmedEvent('BIRT')): ?>
                <?= $person->getConfirmedEvent('BIRT')->getDate(); ?>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($person->getConfirmedEvent('DEAT')): ?>
                <?= $person->getConfirmedEvent('DEAT')->getDate(); ?>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($person->getConfirmedParents()): ?>
                <a href="<?= $person->getConfirmedParents()->getRelationship()->getMother()->getId(); ?>">
                    <?= $person->getConfirmedParents()->getRelationship()->getMother()->getConfirmedName()->getSurnameFirst(); ?></a>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($person->getConfirmedParents()): ?>
                <a href="<?= $person->getConfirmedParents()->getRelationship()->getFather()->getId(); ?>">
                    <?= $person->getConfirmedParents()->getRelationship()->getFather()->getConfirmedName()->getSurnameFirst(); ?></a>
                <?php endif; ?>
            </td>
            <td></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="pagination pagination-small pagination-right">
    <ul>
        <li class="disabled"><a href="#">Prev</a></li>
        <li class="disabled"><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">Next</a></li>
    </ul>
</div>

