
<h2>People</h2>

<form class="form-search">
    <input type="text" class="input-medium search-query">
    <button type="submit" class="btn">Search</button>
</form>

<table class="table table-striped table-hover">
    <thead>
        <th>Name</th>
        <th>Born</th>
        <th>Died</th>
        <th>Mother</th>
        <th>Father</th>
        <th>&nbsp;</th>
    </thead>
    <tbody>
        <?php #foreach ($this->people as $person): //foreach ($this->person->getEvents() as $event): ?>
        <tr>
            <td><a href="/people/view/<?php #echo $person->getId(); ?>">Somebody</a></td>
            <td>Sometime</td>
            <td>Never</td>
            <td>Someone Else</td>
            <td>Someone Elser</td>
            <td></td>
        </tr>
        <?php #endforeach; ?>
    </tbody>
</table>

<div class="pagination pagination-small pagination-right">
    <ul>
        <li class="disabled"><a href="#">Prev</a></li>
        <li class="disabled"><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">Next</a></li>
    </ul>
</div>

