<h2 xmlns="http://www.w3.org/1999/html"><?= $person->getConfirmedName()->getFullName(); ?></h2>

<?php if ($person->getConfirmedParents()):
    $parents = $person->getConfirmedParents();
    $father = $parents->getRelationship()->getFather();
    $mother = $parents->getRelationship()->getMother();
    ?>
<p>
    <?= $person->getGender() == 'F' ? 'Daughter' : 'Son'; ?> of
    <a href="/people/view/<?= $father->getId() ?>"><?= $father->getConfirmedName()->getGivenName() ?></a> and
    <a href="/people/view/<?= $mother->getId() ?>"><?= $mother->getConfirmedName()->getFullName() ?></a>.
</p>
<?php endif; ?>

<div class="tabbable" id="person-tabs">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#generic-information" data-toggle="tab">Generic Information</a></li>
        <li><a href="#names" data-toggle="tab">Names/Aliases <span class="badge badge-inverse"><?= count($this->person->getNames()); ?></span></a></li>
        <li><a href="#events" data-toggle="tab">Events <span class="badge badge-inverse"><?= count($this->person->getEvents()); ?></span></a></li>
        <li><a href="#attributes" data-toggle="tab">Attributes <span class="badge badge-inverse"><?= count($this->person->getAttributes()); ?></span></a></li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="#">General Sources <span class="badge badge-info">1</span></a></li>
            </ul>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="generic-information">



            <div class="container-fluid">
                <form class="form-horizontal" id="person-quick-save">
                    <input type="hidden" name="person_id" value="<?= '' #$this->person->getId(); ?>">
                    <input type="hidden" name="person_name_id" value="<?= '' #$this->person->getPersonNameId(); ?>">
                    <div class="row-fluid">
                        <div class="span12">
                            <div class="row-fluid">
                                <div class="span6 bgcolor">
                                    <div class="control-group">
                                        <label class="control-label" for="given_name">Given Name</label>
                                        <div class="controls">
                                            <input type="text" id="given_name" name="given_name" value="<?= 'Tillotson T.' #$this->person->getGivenName(); ?>">
                                        </div>
                                    </div>
                                </div><!--/span-->
                                <div class="span6 bgcolor">
                                    <div class="control-group">
                                        <label class="control-label" for="surname">Surname</label>
                                        <div class="controls">
                                            <input type="text" id="surname" name="surname" value="<?= 'Terrell' #$this->person->getSurname(); ?>">
                                        </div>
                                    </div>
                                </div><!--/span-->
                            </div><!--/row-->
                            <div class="row-fluid">
                                <div class="span6 bgcolor">
                                    <div class="control-group">
                                        <label class="control-label" for="birth_date">Birth Date</label>
                                        <div class="controls">
                                            <input type="text" id="birth_date" name="birth_date" value="<?= '04 Mar 1821' #$this->person->getBirthDate(); ?>">
                                        </div>
                                    </div>
                                </div><!--/span-->
                                <div class="span6 bgcolor">
                                    <div class="control-group">
                                        <label class="control-label" for="birth_location">Birth Location</label>
                                        <div class="controls">
                                            <input type="text" id="birth_location" name="birth_location" value="<?= 'Ohio' #$this->person->getBirthLocation(); ?>">
                                        </div>
                                    </div>
                                </div><!--/span-->
                            </div><!--/row-->
                            <div class="row-fluid">
                                <div class="span6 bgcolor">
                                    <div class="control-group">
                                        <label class="control-label" for="death_date">Death Date</label>
                                        <div class="controls">
                                            <input type="text" id="death_date" name="death_date" value="<?= '23 Jan 1900' #$this->person->getDeathDate(); ?>">
                                        </div>
                                    </div>
                                </div><!--/span-->
                                <div class="span6 bgcolor">
                                    <div class="control-group">
                                        <label class="control-label" for="death_location">Death Location</label>
                                        <div class="controls">
                                            <input type="text" id="death_location" name="death_location" value="<?= 'Paris Township, Kent County, Michigan' #$this->person->getDeathLocation(); ?>">
                                        </div>
                                    </div>
                                </div><!--/span-->
                            </div><!--/row-->
                        </div>
                    </div>

                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary pull-right">Save</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="tab-pane" id="names">
            <div id="edit-name-dialog" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 id="myModalLabel">Edit Person Name</h4>
                </div>
                <div class="modal-body">


                    <div class="row-fluid">
                        <div class="span12">
                            <div class="row-fluid">
                                <div class="span6 bgcolor">
                                    <div class="control-group">
                                        <label class="control-label" for="given_name">Given Name: </label>
                                        <div class="controls">
                                            <input type="text" id="dialog-name-given" name="given_name" value="<?= 'Tillotson T.' #$this->person->getGivenName(); ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="span6 bgcolor">
                                    <div class="control-group">
                                        <label class="control-label" for="surname">Surname: </label>
                                        <div class="controls">
                                            <input type="text" id="dialog-name-surname" name="surname" value="<?= 'Terrell' #$this->person->getSurname(); ?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row-fluid">
                                <div class="span6 bgcolor">
                                    <div class="control-group">
                                        <label class="control-label" for="birth_date">Prefix: </label>
                                        <div class="controls">
                                            <input type="text" id="dialog-name-prefix" name="prefix" value="<?= '' #$this->person->getBirthDate(); ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="span6 bgcolor">
                                    <div class="control-group">
                                        <label class="control-label" for="birth_location">Suffix: </label>
                                        <div class="controls">
                                            <input type="text" id="dialog-name-suffix" name="suffix" value="<?= '' #$this->person->getBirthLocation(); ?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row-fluid">
                                <div class="span6 bgcolor">
                                    <div class="control-group">
                                        <label class="control-label" for="death_date">Nickname: </label>
                                        <div class="controls">
                                            <input type="text" id="dialog-name-nickname" name="nickname" value="<?= '' #$this->person->getDeathDate(); ?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                    <button class="btn btn-primary">Save changes</button>
                </div>
            </div>

            <table class="table table-striped table-hover">
                <thead>
                    <th>Prefix</th>
                    <th>Given Name</th>
                    <th>Nickname</th>
                    <th>Surname</th>
                    <th>Suffix</th>
                    <th></th>
                </thead>
                <tbody>
                    <?php foreach ($this->person->getNames() as $name): ?>
                    <tr>
                        <td></td>
                        <td><?= $name->getGivenName(); ?></td>
                        <td></td>
                        <td><?= $name->getSurname(); ?></td>
                        <td></td>
                        <td style="width:180px">
                            <a class="btn btn-inverse btn-small" class="edit-name" ref="{person_name_id}" href="#edit-name-dialog" data-toggle="modal">
                                <i class="icon-pencil icon-white"></i> Edit
                            </a>
                            <a class="btn btn-inverse btn-small" href="#">
                                <i class="icon-book icon-white"></i> Sources (<?= count($name->getSources()); ?>)</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="events">
            <table class="table table-striped table-hover">
                <thead>
                    <th>Type</th>
                    <th>Date</th>
                    <th>Location</th>
                    <th>&nbsp;</th>
                </thead>
                <tbody>
                    <?php foreach ($this->person->getEvents() as $event): ?>
                    <tr>
                        <td><?= $event->getType(); ?></td>
                        <td><?= $event->getDate(); ?></td>
                        <td><?= $event->getLocation() ? $event->getLocation()->getDescription() : ''; ?></td>
                        <td style="width:180px">
                            <a class="btn btn-inverse btn-small" class="edit-name" ref="{person_name_id}" href="#edit-name-dialog" data-toggle="modal">
                                <i class="icon-pencil icon-white"></i> Edit
                            </a>
                            <a class="btn btn-inverse btn-small" href="#">
                                <i class="icon-book icon-white"></i> Sources (<?= count($event->getSources()); ?>)</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="attributes">
            <table class="table table-striped table-hover">
                <thead>
                    <th>Type</th>
                    <th>Date</th>
                    <th>Description</th>
                    <th>Location</th>
                    <th></th>
                </thead>
                <tbody>
                    <?php foreach ($this->person->getAttributes() as $attribute): ?>
                    <tr>
                        <td><?= $attribute->getType() ?></td>
                        <td><?= $attribute->getDate() ?></td>
                        <td><?= $attribute->getDescription() ?></td>
                        <td><?= $attribute->getLocation() ? $attribute->getLocation()->getDescription() : '' ?></td>
                        <td style="width:180px">
                            <a class="btn btn-inverse btn-small" class="edit-name" ref="{person_name_id}" href="#edit-name-dialog" data-toggle="modal">
                                <i class="icon-pencil icon-white"></i> Edit
                            </a>
                            <a class="btn btn-inverse btn-small" href="#">
                                <i class="icon-book icon-white"></i> Sources (<?= count($attribute->getSources()); ?>)</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<h3>Relationships</h3>

<div class="tabbable" id="relationship-tabs">
    <ul class="nav nav-tabs">
        <?php foreach ($this->person->getRelationships() as $relationship):
            $spouse = $relationship->getSpouseOf($this->person); ?>
        <li>
            <a href="#spouse-<?= $relationship->getId() ?>-children" data-toggle="tab">
                <?= $spouse->getConfirmedName()->getFullName() ?>
                <span class="badge badge-inverse"><?= count($relationship->getChildren()) ?></span></a>
        </li>
        <?php endforeach; ?>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li></li>
            </ul>
        </li>
    </ul>
    <div class="tab-content">
        <?php foreach ($this->person->getRelationships() as $count => $relationship): ?>
        <div class="tab-pane<?= $count == 0 ? ' active' : '' ?>" id="spouse-<?= $relationship->getId() ?>-children">
            <h4>Children</h4>

            <table class="table table-striped table-hover">
                <thead>
                    <th>Name</th>
                    <th>Born</th>
                    <th>Died</th>
                    <th>&nbsp;</th>
                </thead>
                <tbody>
                <?php foreach ($relationship->getChildren() as $parent): ?>
                <tr>
                    <td>
                        <a href="/people/view/<?= $parent->getPerson()->getId() ?>">
                            <?= $parent->getPerson()->getConfirmedName()->getGivenName() ?></a>
                    </td>
                    <td>
                        <?php if ($parent->getPerson()->getConfirmedEvent('BIRT')): ?>
                        <?= $parent->getPerson()->getConfirmedEvent('BIRT')->getDate(); ?>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($parent->getPerson()->getConfirmedEvent('DEAT')): ?>
                        <?= $parent->getPerson()->getConfirmedEvent('DEAT')->getDate(); ?>
                        <?php endif; ?>
                    </td>
                    <td style="width:180px">
                        <a class="btn btn-inverse btn-small edit-name" ref="{person_name_id}" href="#edit-name-dialog" data-toggle="modal">
                            <i class="icon-pencil icon-white"></i> Edit
                        </a>
                        <a class="btn btn-inverse btn-small" href="#">
                            <i class="icon-book icon-white"></i> Sources (<?= count($parent->getSources()); ?>)</a>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php endforeach; ?>
    </div>
</div>


<script type="text/javascript">
    $('#relationship-tabs a:first').tab('show');

    $('#person-tabs .nav-tabs a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    });

    $('#relationship-tabs .nav-tabs a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    });

    $('form#person-quick-save').on('submit', function(e) {
        e.preventDefault();

        $.ajax({
            url: '/people/quick-save',
            type: 'post',
            data: $(this).serialize(),
            error: function (xhr, status, error) {

            },
            success: function (data, status, xhr) {

            }
        });
    });
</script>
