
<h2>Places</h2>

<form class="form-search">
    <input type="text" class="input-medium search-query">
    <button type="submit" class="btn">Search</button>
</form>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Description</th>
            <th>City</th>
            <th>State/Province</th>
            <th>Country</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $location): ?>
        <tr>
            <td>
                <a href="/places/view/<?= $location->getId(); ?>">
                    <?= $location->getDescription(); ?></a>
            </td>
            <td>
                <?= $location->getCity(); ?>
            </td>
            <td>
                <?= $location->getStateProvince(); ?>
            </td>
            <td>
                <?= $location->getCountry(); ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?= $this->paginationControl($this->paginator, 'Sliding', 'layout/pagination', array('route' => 'places')); ?>
