
<h2><?= $this->location->getDescription() ?></h2>

<?php if ($this->location->getLatitude() && $this->location->getLongitude()):
    $mapExtLink = 'http://www.openstreetmap.org/?lat=' . $this->location->getLatitude() .
        '&amp;lon=' . $this->location->getLongitude() . '&amp;zoom=12&amp;layers=M' .
        '&amp;mlat=' . $this->location->getLatitude() . '&amp;mlon=' . $this->location->getLongitude(); ?>

<style type="text/css"> img { max-width:none; } </style>
<div id="mapdiv" style="width:400px;height:300px;"></div>
<a href="<?= $mapExtLink ?>">View a Larger Map on OpenStreetMap</a>


<script src="http://www.openlayers.org/api/OpenLayers.js"></script>
<script>
    map = new OpenLayers.Map("mapdiv");
    map.addLayer(new OpenLayers.Layer.OSM());

    var lonLat = new OpenLayers.LonLat(<?= $this->location->getLongitude() ?>, <?=$this->location->getLatitude() ?>)
        .transform(
            new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
            map.getProjectionObject() // to Spherical Mercator Projection
        );

    var zoom=12;

    var markers = new OpenLayers.Layer.Markers('Markers');
    map.addLayer(markers);

    markers.addMarker(new OpenLayers.Marker(lonLat));

    map.setCenter(lonLat, zoom);
</script>
<?php endif; ?>
