<?= $this->doctype(); ?>
<html lang="en" ng-app="branchesApp">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Branches')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?= $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->appendStylesheet($this->basePath() . '/css/style.css')
        ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css') ?>

    <?= $this->headScript()->prependFile($this->basePath() . '/js/jquery.min.js')
        ->appendFile($this->basePath() . '/js/bootstrap.min.js') ?>
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/">
                <img src="/images/leaf.png" alt="<?= $this->translate('Branches') ?>" />
                <?= $this->translate('Branches') ?>
            </a>
            <?= $this->navigation('Navigation')->menu()->setPartial('layout/menu')->render() ?>
        </div>
    </div>
</div>
<div class="container">
    <?= $this->content ?>
    <hr>
    <footer>
        <p>Branches.</p>
    </footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
