<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute(
    'action',
    $this->url('people/default', ['action' => 'add-event', 'id' => $this->id])
);
?>

<?= $this->form()->openTag($this->form) ?>
<?= $this->formHidden($this->form->get('event')->get('place')->get('id')) ?>
<?= $this->standardSelectElement($this->form, 'event.type.id') ?>
<?= $this->standardTextElement($this->form, 'event.date') ?>
<?= $this->standardTextElement($this->form, 'event.place.description') ?>

<?php /*
    <div class="form-group">
        <?= $this->standardFormElement('event.type.id') ?>
        <?= $this->formLabel($this->form->get('event')->get('type')->get('id')) ?>
        <?= $this->formSelect($this->form->get('event')->get('type')->get('id')->setAttribute('class', 'form-control')) ?>
        <?= $this->formElementErrors($this->form->get('event')->get('type')->get('id'), ['class' => 'form-errors']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($this->form->get('event')->get('date')) ?>
        <?= $this->formText($this->form->get('event')->get('date')->setAttribute('class', 'form-control')) ?>
        <?= $this->formElementErrors($this->form->get('event')->get('date'), ['class' => 'form-errors']) ?>
    </div>
    <div class="form-group">
        <?= $this->formHidden($this->form->get('event')->get('place')->get('id')) ?>
        <?= $this->formLabel($this->form->get('event')->get('place')->get('description')) ?>
        <?= $this->formText($this->form->get('event')->get('place')->get('description')
                ->setAttribute('class', 'form-control typeahead')) ?>
        <?= $this->formElementErrors($this->form->get('event')->get('place')->get('description'), ['class' => 'form-errors']) ?>
    </div>
 */ ?>

<?= $this->form()->closeTag() ?>

<script type="text/javascript">
    var placesTemplate = [
        '<div><strong>{{description}}</strong></div>',
        '<div>{{address1}}, {{city}}, {{state_province}}, {{postal_code}}</div>'
    ].join('');

    $('form#person-event-form .typeahead').typeahead(null, {
        name: 'places',
        displayKey: 'description',
        template: placesTemplate,
        source: places.ttAdapter()
    });

    $('form#person-event-form .typeahead').bind('typeahead:selected', function(obj, datum, name) {
        $('input[name="event[place][id]"]').val(datum.id);
    });
</script>
