
<h2>People</h2>

<form class="form-search">
    <input type="text" class="input-medium search-query">
    <button type="submit" class="btn">Search</button>
</form>

<table class="table table-striped table-hover">
    <thead>
        <th>Name</th>
        <th>Born</th>
        <th>Died</th>
        <th>Mother</th>
        <th>Father</th>
        <th>&nbsp;</th>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $person): ?>
        <tr>
            <td>
                <a href="/people/view/<?= $person->getId(); ?>">
                    <?= $person->getConfirmedName()->getSurnameFirst(); ?></a>
            </td>
            <td>
                <?php if ($person->getConfirmedEvent('BIRT')): ?>
                <?= $person->getConfirmedEvent('BIRT')->getDate(); ?>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($person->getConfirmedEvent('DEAT')): ?>
                <?= $person->getConfirmedEvent('DEAT')->getDate(); ?>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($person->getConfirmedParents()): ?>
                <a href="<?= $person->getConfirmedParents()->getRelationship()->getMother()->getId(); ?>">
                    <?= $person->getConfirmedParents()->getRelationship()->getMother()->getConfirmedName()->getSurnameFirst(); ?></a>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($person->getConfirmedParents()): ?>
                <a href="<?= $person->getConfirmedParents()->getRelationship()->getFather()->getId(); ?>">
                    <?= $person->getConfirmedParents()->getRelationship()->getFather()->getConfirmedName()->getSurnameFirst(); ?></a>
                <?php endif; ?>
            </td>
            <td></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>


<?= $this->paginationControl($this->paginator, 'Sliding', 'layout/pagination', array('route' => 'people')); ?>

