<?= $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Branches')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?= $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
    <!-- Scripts -->
    <?= $this->headScript()->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="<?= $this->url('home') ?>"><?= $this->translate('Branches') ?></a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class="active"><a href="<?= $this->url('home') ?>"><?= $this->translate('Home') ?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <?= $this->content; ?>
        <hr>
        <footer>
            <p>Branches.</p>
        </footer>
    </div> <!-- /container -->
    <?= $this->inlineScript() ?>
</body>
</html>
