<?= $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Branches')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?= $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->appendStylesheet($this->basePath() . '/css/style.css')
        ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css') ?>
    
    <?= $this->headScript()->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="/">
                    <img src="/images/leaf.png" style="height: 24px" />
                    <?= $this->translate('Branches') ?>
                </a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li><a href="/">Home</a></li>
                        <li><a href="/people">People</a></li>
                        <li><a href="/places">Places</a></li>
                        <li><a href="/media">Media</a></li>
                        <li><a href="/sources">Sources</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <?= $this->content; ?>
        <hr>
        <footer>
            <p>Branches.</p>
        </footer>
    </div> <!-- /container -->
    <?= $this->inlineScript() ?>
</body>
</html>
