<?= $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle(isset($this->pageTitle) ? $this->pageTitle : 'Branches') ?>
    <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <?= $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->appendStylesheet($this->basePath() . '/css/style.css') ?>
    
    <?= $this->headScript()->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
</head>
<body>
    <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><?= $this->translate('Branches') ?></a>
            </div>
            <div class="navbar-collapse collapse">
                <?= $this->navigation('Navigation')->menu()->setPartial('layout/menu')->render() ?>
            </div>
        </div>
    </div>
    <div class="container">
        <?= $this->content; ?>
        <hr>
        <footer>
            <p>Branches.</p>
        </footer>
    </div>
    <?= $this->inlineScript() ?>
</body>
</html>
