<!DOCTYPE html>
<html lang="en">
<head>
    <title>Branches</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/css/vendor/jquery-ui.min.css">
    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/css/layout.css">
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img alt="" src="/images/logo.png">
                </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">Home</a></li>
                    <li><a href="/people">People</a></li>
                    <li><a href="#contact">Places</a></li>
                    <li><a href="#contact">Media</a></li>
                    <li><a href="#contact">Sources</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container">
        <?= $this->content ?>
    </div>

    <div class="footer">
        <div class="container">
            <p class="text-muted">Place sticky footer content here.</p>
        </div>
    </div>

    <script src="/js/vendor/jquery.min.js"></script>
    <script src="/js/vendor/jquery-ui.min.js"></script>
    <script src="/js/vendor/bootstrap.min.js"></script>
    <script src="/js/application/app.js"></script>
    <script src="/js/application/modal.js"></script>
    <script src="/js/vendor/typeahead.bundle.min.js"></script>

    <?= $this->viewBasedJs($this->viewModel()->getCurrent()) ?>
    <?= $this->headScript() ?>
</body>
</html>
