<!DOCTYPE html>
<html lang="en">
<head>
    <title>Branches</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/css/vendor/jquery-ui.min.css">
    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/css/layout.css">
    <link rel="stylesheet" type="text/css" href="/css/login.css">
</head>
<body>

    <div class="container">
        <?= $this->content ?>
    </div>

    <script src="/js/vendor/jquery.min.js"></script>
    <script src="/js/vendor/bootstrap.min.js"></script>

    <?= $this->viewBasedJs($this->viewModel()->getCurrent()) ?>
    <?= $this->headScript() ?>
</body>
</html>
